services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-80}:80"
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - sip-storage:/var/www/html/storage/app
    networks:
      - sip

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - sip-mariadb:/var/lib/mysql
    networks:
      - sip
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      retries: 5
      interval: 5s
      timeout: 5s

networks:
  sip:
    driver: bridge

volumes:
  sip-mariadb:
    driver: local
  sip-storage:
    driver: local
